version: '3'
services:
  database:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - '.env'
  elastic:
    image: elasticsearch:7.12.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    container_name: elastic-om30
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  back:
    build: ./back
    command: bash -c "rm -f tmp/pids/server/pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/back
    ports:
      - 3000:3000
    depends_on:
      - database
      - elastic
    env_file:
      - '.env'
    stdin_open: true
    tty: true

  front:
    build: ./front
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    depends_on:
      - back
    volumes:
      - ./front:/front
      - /front/node_modules

volumes:
  db_data:
  esdata: